### ISSUE TITLE
captcha not solved !

### ISSUE THREAD

**Issue by whitestorm007** [Body-Alhoha/turnaround#7]
@Body-Alhoha  - this used to work well before, but is now failing consistently. Wondering if you are facing the same problem too?

{
        "sitekey": "0x4AAAAAAAEN8bxixfR5WnuT",
        "url": "https://rewards.bing.com/redeem/checkout",
        "invisible": false
      }

**Comment by larry-ct** [comment]
+1

**Comment by whitestorm007** [comment]
???

**Comment by minecraft8093** [comment]
same

**Comment by epicwhale** [comment]
Anyone figured any hints towards what's exactly causing the failure?

**Comment by whitestorm007** [comment]
Yes , cf block all chrome drivers, and other browser  , including undetacted - chrome driver , but ,natural chrome , which can be create by  executable_path is working

**Comment by Body-Alhoha** [comment]
duplicate issue, see #6

**Comment by nandish486** [comment]
> Yes , cf block all chrome drivers, and other browser , including undetacted - chrome driver , but ,natural chrome , which can be create by executable_path is working

how to  use normal browser in playwright? how did u did?

**Comment by whitestorm007** [comment]
> > Yes , cf block all chrome drivers, and other browser , including undetacted - chrome driver , but ,natural chrome , which can be create by executable_path is working
> 
> how to use normal browser in playwright? how did u did?


i use selenium-webdriver
const {Builder, By, Key, until, Capabilities} = require("selenium-webdriver");
const chrome = require("selenium-webdriver/chrome");

const loginUrl = "your url";
async function loginToOutlook(url) {
  return new Promise(async (resolve, reject) => {
    var chromeCapabilities = Capabilities.chrome();

    var driver = await new Builder()
      .withCapabilities(chromeCapabilities)
      .forBrowser("chrome")
      .setChromeOptions(
        new chrome.Options().addArguments(
          "--proxy-server=socks5://localhost:1338"
        )
      )
      .build();

**Comment by nandish486** [comment]
> "--proxy-server=socks5://localhost:1338"

can u provide for python ?

**Comment by whitestorm007** [comment]
don't have python code for this , but u can try chatGpt for it
